### ISSUE TITLE
Two 404 Links in Footer

### ISSUE THREAD

**Issue by colinator27** [SharpScratchMod/SharpScratchMod.github.io#2]
Just wanted to say that there are two broken links in the footer of the webpage. (/about and /news)

It brings you to the 404 page from GitHub. I'd suggest removing those two links. :)

**Comment by Mrcomputer1** [comment]
I have disabled the About link and changed the path of the news link to a blogger blog I made for Sharp

**Comment by colinator27** [comment]
Nice! :D
