### ISSUE TITLE
No padding on site?

### ISSUE THREAD

**Issue by colinator27** [SharpScratchMod/SharpScratchMod.github.io#3]
As you can see on the site, there is no space between the left of the webpage and the text on the webpage. I came up with some code that should help fix it.

You should add this CSS code:
`
.padding-main {
  padding-left: 15px;
}
`
HTML for navbar the Sharp text:
`
 <div class="padding-main"><a href="#" class="brand-logo">Sharp</a></div>
`
For the rest of it, surround the main content (no footer included or navbar) with the div with the padding-main class:
`
 <div class="padding-main"></div>
`
It's just a simple design choice, not so sure if you want to use it but in my personal opinion it looks a bit better.

**Comment by Mrcomputer1** [comment]
I will fix this soon. I think I might be able to use `<div class="container"></div>`.

**Comment by Mrcomputer1** [comment]
Fixed! :smile:

**Comment by colinator27** [comment]
Okie! :D
