### ISSUE TITLE
Question about Sharp

### ISSUE THREAD

**Issue by AmazingMech2418** [SharpScratchMod/SharpScratchMod.github.io#4]
How did you make this? I'm thinking about converting some of the blocks to be in a Scratch extension. I'll give credit though.

**Comment by Mrcomputer1** [comment]
We made this by forking Scratch's source code ([LLK/scratch-flash](https://github.com/llk/scratch-flash)) and modifying it. The source for this Scratch mod is located at [SharpScratchMod/Sharp](https://github.com/SharpScratchMod/Sharp).  The code for our blocks can be found at https://github.com/SharpScratchMod/Sharp/tree/master/src/primitives (Note: code for Scratch's blocks are also there). 

If you do convert some of the blocks please comment the link to it so I can have a look.

Also, sorry for the late reply.

**Comment by AmazingMech2418** [comment]
I meant how do the blocks work. I could probably convert the actionScript to JS, but don't know the actionScript code since my computer can only run and not view the code.

**Comment by Mrcomputer1** [comment]
The ActionScript code for our blocks can be found at https://github.com/SharpScratchMod/Sharp/tree/master/src/primitives (except for blocks like for each and code section, which are located in the interpreter). If you need help finding a block you can ask me.

**Comment by AmazingMech2418** [comment]
Thank you!
